name: DataDonor
options:
  bundleIdPrefix: la.tsel
targets:
  DataDonor:
    type: application
    platform: iOS
    scheme: {}
    deploymentTarget: "16.0"
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: "RUD2L7H988"
      TARGETED_DEVICE_FAMILY: "1"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: "Data Donor"
        LSApplicationCategoryType: "public.app-category.healthcare-fitness"
        NSHealthShareUsageDescription: "DataDonor needs access to read your health data to securely sync it to your personal server."
        NSHealthUpdateUsageDescription: "DataDonor needs access to write your health data to securely sync it to your personal server."
        NSLocationWhenInUseUsageDescription: "DataDonor needs your location to detect the current Wi-Fi network and verify you are connected to your target server."
        NSCameraUsageDescription: "DataDonor needs access to the camera to scan your API Key QR Code."
        NSLocalNetworkUsageDescription: "DataDonor needs access to your local network to discover your Fastify syncing server automatically."
        NSBonjourServices:
          - "_datadonor._tcp"
        BGTaskSchedulerPermittedIdentifiers:
          - "la.tsel.datadonor.backgroundSync"
        UIBackgroundModes:
          - "fetch"
          - "processing"
    entitlements:
      path: DataDonor.entitlements
